"""new schemas

Revision ID: 25b6b5a8adca
Revises: fbe2c7780d0f
Create Date: 2026-04-17 16:57:50.493961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b6b5a8adca'
down_revision: Union[str, None] = 'fbe2c7780d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('photo_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_photos_client_id'), 'client_photos', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_photos_file_path'), 'client_photos', ['file_path'], unique=False)
    op.create_index(op.f('ix_client_photos_id'), 'client_photos', ['id'], unique=False)
    op.create_index(op.f('ix_client_photos_photo_type'), 'client_photos', ['photo_type'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_brand'), 'clients', ['brand'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_model'), 'clients', ['model'], unique=False)
    op.drop_index(op.f('ix_cars_brand'), table_name='cars')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_model'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_car_images_client_id'), table_name='car_images')
    op.drop_index(op.f('ix_car_images_file_path'), table_name='car_images')
    op.drop_index(op.f('ix_car_images_id'), table_name='car_images')
    op.drop_index(op.f('ix_car_images_photo_type'), table_name='car_images')
    op.drop_table('car_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('car_images_pkey'))
    )
    op.create_index(op.f('ix_car_images_photo_type'), 'car_images', ['photo_type'], unique=False)
    op.create_index(op.f('ix_car_images_id'), 'car_images', ['id'], unique=False)
    op.create_index(op.f('ix_car_images_file_path'), 'car_images', ['file_path'], unique=False)
    op.create_index(op.f('ix_car_images_client_id'), 'car_images', ['client_id'], unique=False)
    op.create_table('cars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cars_pkey'))
    )
    op.create_index(op.f('ix_cars_model'), 'cars', ['model'], unique=False)
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_index(op.f('ix_cars_brand'), 'cars', ['brand'], unique=False)
    op.drop_index(op.f('ix_clients_model'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_brand'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_client_photos_photo_type'), table_name='client_photos')
    op.drop_index(op.f('ix_client_photos_id'), table_name='client_photos')
    op.drop_index(op.f('ix_client_photos_file_path'), table_name='client_photos')
    op.drop_index(op.f('ix_client_photos_client_id'), table_name='client_photos')
    op.drop_table('client_photos')
    # ### end Alembic commands ###
