"""initial schema

Revision ID: 50430fac5f4e
Revises: 
Create Date: 2026-04-11 05:05:00.845581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50430fac5f4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('photo_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_images_client_id'), 'car_images', ['client_id'], unique=False)
    op.create_index(op.f('ix_car_images_file_path'), 'car_images', ['file_path'], unique=False)
    op.create_index(op.f('ix_car_images_id'), 'car_images', ['id'], unique=False)
    op.create_index(op.f('ix_car_images_photo_type'), 'car_images', ['photo_type'], unique=False)
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_brand'), 'cars', ['brand'], unique=False)
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_index(op.f('ix_cars_model'), 'cars', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cars_model'), table_name='cars')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_brand'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_car_images_photo_type'), table_name='car_images')
    op.drop_index(op.f('ix_car_images_id'), table_name='car_images')
    op.drop_index(op.f('ix_car_images_file_path'), table_name='car_images')
    op.drop_index(op.f('ix_car_images_client_id'), table_name='car_images')
    op.drop_table('car_images')
    # ### end Alembic commands ###
